// ============================================================
// PRE-COMPUTED KPI DATA — Generated from 25,000-invoice SQLite DB
// Auto-generated by prisma/compute-dashboard-data.ts
// DO NOT EDIT MANUALLY — re-run the compute script to update
// ============================================================

export type QuarterKey = "Q1" | "Q2" | "Q3" | "Q4" | "All";

export interface AgingBucket {
  bucket: string;
  key: string;
  count: number;
  amount: number;
  percentage: number;
  color: string;
}

export interface MonthlyPoint {
  month: string;
  value: number;
}

export interface WeeklyPoint {
  week: string;
  value: number;
}

export interface WaterfallPoint {
  month: string;
  value: number;
  label: string;
}

export interface QuarterData {
  summary: {
    totalInvoices: number;
    openInvoices: number;
    clearedInvoices: number;
    overdueInvoices: number;
    totalOpenAR: number;
    overdueAR: number;
    currentAR: number;
    totalSales: number;
  };
  executive: {
    dso: { overall: number; monthly: MonthlyPoint[] };
    overdueRatio: { overall: number; monthly: MonthlyPoint[] };
    revenueAtRisk: { value: number };
    receivablesTurnover: { overall: number; monthly: MonthlyPoint[] };
    netARMovement: { monthly: WaterfallPoint[] };
  };
  collection: {
    cei: { overall: number; monthly: MonthlyPoint[] };
    onTimePayment: { weekly: WeeklyPoint[] };
    collectionEffectiveness: { weekly: WeeklyPoint[] };
    creditPeriodEffectiveness: { data: { creditPeriod: string; value: number }[] };
  };
  aging: {
    buckets: AgingBucket[];
    overdueDensity: { count: number; value: number };
    peakExposure: { amount: number; invoiceNo: string; companyCode: string; daysOverdue: number };
  };
  operational: {
    invoiceToCash: { p50: number; p90: number };
    creditPeriodUtilization: { overall: number; monthly: MonthlyPoint[] };
    daysToClearBacklog: { weekly: WeeklyPoint[] };
  };
}

export const COMPUTED_KPI_DATA: Record<QuarterKey, QuarterData> = {
  "Q1": {
    "summary": {
      "totalInvoices": 5123,
      "openInvoices": 1228,
      "clearedInvoices": 3895,
      "overdueInvoices": 1228,
      "totalOpenAR": 4144307176,
      "overdueAR": 4144307176,
      "currentAR": 0,
      "totalSales": 24812764880
    },
    "executive": {
      "dso": {
        "overall": 15,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 4.9
          },
          {
            "month": "May'25",
            "value": 6
          },
          {
            "month": "Jun'25",
            "value": 4.3
          }
        ]
      },
      "overdueRatio": {
        "overall": 100,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 100
          },
          {
            "month": "May'25",
            "value": 100
          },
          {
            "month": "Jun'25",
            "value": 100
          }
        ]
      },
      "revenueAtRisk": {
        "value": 50.7
      },
      "receivablesTurnover": {
        "overall": 39.1,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 12.5
          },
          {
            "month": "May'25",
            "value": 5.7
          },
          {
            "month": "Jun'25",
            "value": 6.4
          }
        ]
      },
      "netARMovement": {
        "monthly": [
          {
            "month": "Apr'25",
            "value": 1310684907,
            "label": "Apr'25"
          },
          {
            "month": "May'25",
            "value": 255256859,
            "label": "May'25"
          },
          {
            "month": "Jun'25",
            "value": -298261264,
            "label": "Jun'25"
          }
        ]
      }
    },
    "collection": {
      "cei": {
        "overall": 84.9,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 83.7
          },
          {
            "month": "May'25",
            "value": 83.2
          },
          {
            "month": "Jun'25",
            "value": 87.8
          }
        ]
      },
      "onTimePayment": {
        "weekly": [
          {
            "week": "W1",
            "value": 0
          },
          {
            "week": "W2",
            "value": 0
          },
          {
            "week": "W3",
            "value": 0
          },
          {
            "week": "W4",
            "value": 0
          },
          {
            "week": "W5",
            "value": 0
          },
          {
            "week": "W6",
            "value": 0
          },
          {
            "week": "W7",
            "value": 0
          },
          {
            "week": "W8",
            "value": 0
          },
          {
            "week": "W9",
            "value": 0
          },
          {
            "week": "W10",
            "value": 0
          },
          {
            "week": "W11",
            "value": 0
          },
          {
            "week": "W12",
            "value": 0
          },
          {
            "week": "W13",
            "value": 0
          }
        ]
      },
      "collectionEffectiveness": {
        "weekly": [
          {
            "week": "W1",
            "value": 0
          },
          {
            "week": "W2",
            "value": 0
          },
          {
            "week": "W3",
            "value": 0
          },
          {
            "week": "W4",
            "value": 0
          },
          {
            "week": "W5",
            "value": 0
          },
          {
            "week": "W6",
            "value": 0
          },
          {
            "week": "W7",
            "value": 0
          },
          {
            "week": "W8",
            "value": 0
          },
          {
            "week": "W9",
            "value": 0
          },
          {
            "week": "W10",
            "value": 0
          },
          {
            "week": "W11",
            "value": 0
          },
          {
            "week": "W12",
            "value": 0
          },
          {
            "week": "W13",
            "value": 0
          }
        ]
      },
      "creditPeriodEffectiveness": {
        "data": [
          {
            "creditPeriod": "7 days",
            "value": 61.3
          },
          {
            "creditPeriod": "15 days",
            "value": 66.6
          },
          {
            "creditPeriod": "30 days",
            "value": 70.4
          },
          {
            "creditPeriod": "45 days",
            "value": 75.7
          },
          {
            "creditPeriod": "60 days",
            "value": 79.8
          }
        ]
      }
    },
    "aging": {
      "buckets": [
        {
          "bucket": "Not Due",
          "key": "NOT_DUE",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#16a34a"
        },
        {
          "bucket": "1-7 days",
          "key": "1_7",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#22c55e"
        },
        {
          "bucket": "8-15 days",
          "key": "8_15",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#3b82f6"
        },
        {
          "bucket": "16-30 days",
          "key": "16_30",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#eab308"
        },
        {
          "bucket": "31-45 days",
          "key": "31_45",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#d97706"
        },
        {
          "bucket": "46-60 days",
          "key": "46_60",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#ea580c"
        },
        {
          "bucket": "60+ days",
          "key": "60_PLUS",
          "count": 1228,
          "amount": 4144307176,
          "percentage": 100,
          "color": "#dc2626"
        }
      ],
      "overdueDensity": {
        "count": 100,
        "value": 100
      },
      "peakExposure": {
        "amount": 140506925,
        "invoiceNo": "2025012738",
        "companyCode": "2000",
        "daysOverdue": 229
      }
    },
    "operational": {
      "invoiceToCash": {
        "p50": 37,
        "p90": 64
      },
      "creditPeriodUtilization": {
        "overall": 133.1,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 135.4
          },
          {
            "month": "May'25",
            "value": 131.4
          },
          {
            "month": "Jun'25",
            "value": 132.6
          }
        ]
      },
      "daysToClearBacklog": {
        "weekly": [
          {
            "week": "W1",
            "value": 0
          },
          {
            "week": "W2",
            "value": 0
          },
          {
            "week": "W3",
            "value": 0
          },
          {
            "week": "W4",
            "value": 0
          },
          {
            "week": "W5",
            "value": 0
          },
          {
            "week": "W6",
            "value": 0
          },
          {
            "week": "W7",
            "value": 0
          },
          {
            "week": "W8",
            "value": 0
          },
          {
            "week": "W9",
            "value": 0
          },
          {
            "week": "W10",
            "value": 0
          },
          {
            "week": "W11",
            "value": 0
          },
          {
            "week": "W12",
            "value": 0
          },
          {
            "week": "W13",
            "value": 0
          }
        ]
      }
    }
  },
  "Q2": {
    "summary": {
      "totalInvoices": 6083,
      "openInvoices": 1380,
      "clearedInvoices": 4703,
      "overdueInvoices": 1380,
      "totalOpenAR": 4830888263,
      "overdueAR": 4830888263,
      "currentAR": 0,
      "totalSales": 30866070569
    },
    "executive": {
      "dso": {
        "overall": 14.1,
        "monthly": [
          {
            "month": "Jul'25",
            "value": 4.6
          },
          {
            "month": "Aug'25",
            "value": 4.9
          },
          {
            "month": "Sep'25",
            "value": 4.5
          }
        ]
      },
      "overdueRatio": {
        "overall": 100,
        "monthly": [
          {
            "month": "Jul'25",
            "value": 100
          },
          {
            "month": "Aug'25",
            "value": 100
          },
          {
            "month": "Sep'25",
            "value": 100
          }
        ]
      },
      "revenueAtRisk": {
        "value": 48.6
      },
      "receivablesTurnover": {
        "overall": 22.3,
        "monthly": [
          {
            "month": "Jul'25",
            "value": 7.1
          },
          {
            "month": "Aug'25",
            "value": 6.9
          },
          {
            "month": "Sep'25",
            "value": 6.1
          }
        ]
      },
      "netARMovement": {
        "monthly": [
          {
            "month": "Jul'25",
            "value": 270788123,
            "label": "Jul'25"
          },
          {
            "month": "Aug'25",
            "value": 251373597,
            "label": "Aug'25"
          },
          {
            "month": "Sep'25",
            "value": -287264807,
            "label": "Sep'25"
          }
        ]
      }
    },
    "collection": {
      "cei": {
        "overall": 86.3,
        "monthly": [
          {
            "month": "Jul'25",
            "value": 86
          },
          {
            "month": "Aug'25",
            "value": 85.5
          },
          {
            "month": "Sep'25",
            "value": 87.3
          }
        ]
      },
      "onTimePayment": {
        "weekly": [
          {
            "week": "W14",
            "value": 0
          },
          {
            "week": "W15",
            "value": 0
          },
          {
            "week": "W16",
            "value": 0
          },
          {
            "week": "W17",
            "value": 0
          },
          {
            "week": "W18",
            "value": 0
          },
          {
            "week": "W19",
            "value": 0
          },
          {
            "week": "W20",
            "value": 0
          },
          {
            "week": "W21",
            "value": 0
          },
          {
            "week": "W22",
            "value": 0
          },
          {
            "week": "W23",
            "value": 0
          },
          {
            "week": "W24",
            "value": 0
          },
          {
            "week": "W25",
            "value": 0
          },
          {
            "week": "W26",
            "value": 0
          },
          {
            "week": "W27",
            "value": 0
          }
        ]
      },
      "collectionEffectiveness": {
        "weekly": [
          {
            "week": "W14",
            "value": 0
          },
          {
            "week": "W15",
            "value": 0
          },
          {
            "week": "W16",
            "value": 0
          },
          {
            "week": "W17",
            "value": 0
          },
          {
            "week": "W18",
            "value": 0
          },
          {
            "week": "W19",
            "value": 0
          },
          {
            "week": "W20",
            "value": 0
          },
          {
            "week": "W21",
            "value": 0
          },
          {
            "week": "W22",
            "value": 0
          },
          {
            "week": "W23",
            "value": 0
          },
          {
            "week": "W24",
            "value": 0
          },
          {
            "week": "W25",
            "value": 0
          },
          {
            "week": "W26",
            "value": 0
          },
          {
            "week": "W27",
            "value": 0
          }
        ]
      },
      "creditPeriodEffectiveness": {
        "data": [
          {
            "creditPeriod": "7 days",
            "value": 67.2
          },
          {
            "creditPeriod": "15 days",
            "value": 58.8
          },
          {
            "creditPeriod": "30 days",
            "value": 72
          },
          {
            "creditPeriod": "45 days",
            "value": 81.9
          },
          {
            "creditPeriod": "60 days",
            "value": 78.9
          }
        ]
      }
    },
    "aging": {
      "buckets": [
        {
          "bucket": "Not Due",
          "key": "NOT_DUE",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#16a34a"
        },
        {
          "bucket": "1-7 days",
          "key": "1_7",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#22c55e"
        },
        {
          "bucket": "8-15 days",
          "key": "8_15",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#3b82f6"
        },
        {
          "bucket": "16-30 days",
          "key": "16_30",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#eab308"
        },
        {
          "bucket": "31-45 days",
          "key": "31_45",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#d97706"
        },
        {
          "bucket": "46-60 days",
          "key": "46_60",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#ea580c"
        },
        {
          "bucket": "60+ days",
          "key": "60_PLUS",
          "count": 1380,
          "amount": 4830888263,
          "percentage": 100,
          "color": "#dc2626"
        }
      ],
      "overdueDensity": {
        "count": 100,
        "value": 100
      },
      "peakExposure": {
        "amount": 119333242,
        "invoiceNo": "2025022453",
        "companyCode": "3000",
        "daysOverdue": 203
      }
    },
    "operational": {
      "invoiceToCash": {
        "p50": 37,
        "p90": 64
      },
      "creditPeriodUtilization": {
        "overall": 130.3,
        "monthly": [
          {
            "month": "Jul'25",
            "value": 132.9
          },
          {
            "month": "Aug'25",
            "value": 130.8
          },
          {
            "month": "Sep'25",
            "value": 127.3
          }
        ]
      },
      "daysToClearBacklog": {
        "weekly": [
          {
            "week": "W14",
            "value": 71.8
          },
          {
            "week": "W15",
            "value": 190.9
          },
          {
            "week": "W16",
            "value": 20.7
          },
          {
            "week": "W17",
            "value": 85.3
          },
          {
            "week": "W18",
            "value": 78.1
          },
          {
            "week": "W19",
            "value": 0
          },
          {
            "week": "W20",
            "value": 39.5
          },
          {
            "week": "W21",
            "value": 430.3
          },
          {
            "week": "W22",
            "value": 0
          },
          {
            "week": "W23",
            "value": 999
          },
          {
            "week": "W24",
            "value": 471.6
          },
          {
            "week": "W25",
            "value": 0
          },
          {
            "week": "W26",
            "value": 22
          },
          {
            "week": "W27",
            "value": 12
          }
        ]
      }
    }
  },
  "Q3": {
    "summary": {
      "totalInvoices": 6512,
      "openInvoices": 1571,
      "clearedInvoices": 4941,
      "overdueInvoices": 1571,
      "totalOpenAR": 6179479025,
      "overdueAR": 6179479025,
      "currentAR": 0,
      "totalSales": 34981250870
    },
    "executive": {
      "dso": {
        "overall": 15.9,
        "monthly": [
          {
            "month": "Oct'25",
            "value": 5.5
          },
          {
            "month": "Nov'25",
            "value": 5.2
          },
          {
            "month": "Dec'25",
            "value": 5.2
          }
        ]
      },
      "overdueRatio": {
        "overall": 100,
        "monthly": [
          {
            "month": "Oct'25",
            "value": 100
          },
          {
            "month": "Nov'25",
            "value": 100
          },
          {
            "month": "Dec'25",
            "value": 100
          }
        ]
      },
      "revenueAtRisk": {
        "value": 50.1
      },
      "receivablesTurnover": {
        "overall": 19.1,
        "monthly": [
          {
            "month": "Oct'25",
            "value": 6.6
          },
          {
            "month": "Nov'25",
            "value": 5.6
          },
          {
            "month": "Dec'25",
            "value": 6.1
          }
        ]
      },
      "netARMovement": {
        "monthly": [
          {
            "month": "Oct'25",
            "value": 577272108,
            "label": "Oct'25"
          },
          {
            "month": "Nov'25",
            "value": -142955471,
            "label": "Nov'25"
          },
          {
            "month": "Dec'25",
            "value": 225841396,
            "label": "Dec'25"
          }
        ]
      }
    },
    "collection": {
      "cei": {
        "overall": 84.6,
        "monthly": [
          {
            "month": "Oct'25",
            "value": 83.7
          },
          {
            "month": "Nov'25",
            "value": 85.3
          },
          {
            "month": "Dec'25",
            "value": 84.9
          }
        ]
      },
      "onTimePayment": {
        "weekly": [
          {
            "week": "W28",
            "value": 0
          },
          {
            "week": "W29",
            "value": 0
          },
          {
            "week": "W30",
            "value": 0
          },
          {
            "week": "W31",
            "value": 0
          },
          {
            "week": "W32",
            "value": 0
          },
          {
            "week": "W33",
            "value": 0
          },
          {
            "week": "W34",
            "value": 0
          },
          {
            "week": "W35",
            "value": 0
          },
          {
            "week": "W36",
            "value": 0
          },
          {
            "week": "W37",
            "value": 0
          },
          {
            "week": "W38",
            "value": 0
          },
          {
            "week": "W39",
            "value": 0
          },
          {
            "week": "W40",
            "value": 0
          }
        ]
      },
      "collectionEffectiveness": {
        "weekly": [
          {
            "week": "W28",
            "value": 0
          },
          {
            "week": "W29",
            "value": 0
          },
          {
            "week": "W30",
            "value": 0
          },
          {
            "week": "W31",
            "value": 0
          },
          {
            "week": "W32",
            "value": 0
          },
          {
            "week": "W33",
            "value": 0
          },
          {
            "week": "W34",
            "value": 0
          },
          {
            "week": "W35",
            "value": 0
          },
          {
            "week": "W36",
            "value": 0
          },
          {
            "week": "W37",
            "value": 0
          },
          {
            "week": "W38",
            "value": 0
          },
          {
            "week": "W39",
            "value": 0
          },
          {
            "week": "W40",
            "value": 0
          }
        ]
      },
      "creditPeriodEffectiveness": {
        "data": [
          {
            "creditPeriod": "7 days",
            "value": 77.7
          },
          {
            "creditPeriod": "15 days",
            "value": 61.8
          },
          {
            "creditPeriod": "30 days",
            "value": 68.9
          },
          {
            "creditPeriod": "45 days",
            "value": 82.7
          },
          {
            "creditPeriod": "60 days",
            "value": 79.2
          }
        ]
      }
    },
    "aging": {
      "buckets": [
        {
          "bucket": "Not Due",
          "key": "NOT_DUE",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#16a34a"
        },
        {
          "bucket": "1-7 days",
          "key": "1_7",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#22c55e"
        },
        {
          "bucket": "8-15 days",
          "key": "8_15",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#3b82f6"
        },
        {
          "bucket": "16-30 days",
          "key": "16_30",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#eab308"
        },
        {
          "bucket": "31-45 days",
          "key": "31_45",
          "count": 17,
          "amount": 156381036,
          "percentage": 2.5,
          "color": "#d97706"
        },
        {
          "bucket": "46-60 days",
          "key": "46_60",
          "count": 87,
          "amount": 748895674,
          "percentage": 12.1,
          "color": "#ea580c"
        },
        {
          "bucket": "60+ days",
          "key": "60_PLUS",
          "count": 1467,
          "amount": 5274202314,
          "percentage": 85.4,
          "color": "#dc2626"
        }
      ],
      "overdueDensity": {
        "count": 100,
        "value": 100
      },
      "peakExposure": {
        "amount": 168769906,
        "invoiceNo": "2025006542",
        "companyCode": "3000",
        "daysOverdue": 170
      }
    },
    "operational": {
      "invoiceToCash": {
        "p50": 37,
        "p90": 64
      },
      "creditPeriodUtilization": {
        "overall": 132.4,
        "monthly": [
          {
            "month": "Oct'25",
            "value": 132.5
          },
          {
            "month": "Nov'25",
            "value": 135.7
          },
          {
            "month": "Dec'25",
            "value": 129.3
          }
        ]
      },
      "daysToClearBacklog": {
        "weekly": [
          {
            "week": "W28",
            "value": 384.1
          },
          {
            "week": "W29",
            "value": 999
          },
          {
            "week": "W30",
            "value": 705
          },
          {
            "week": "W31",
            "value": 999
          },
          {
            "week": "W32",
            "value": 430.4
          },
          {
            "week": "W33",
            "value": 999
          },
          {
            "week": "W34",
            "value": 762.2
          },
          {
            "week": "W35",
            "value": 999
          },
          {
            "week": "W36",
            "value": 999
          },
          {
            "week": "W37",
            "value": 40.5
          },
          {
            "week": "W38",
            "value": 999
          },
          {
            "week": "W39",
            "value": 999
          },
          {
            "week": "W40",
            "value": 88.6
          }
        ]
      }
    }
  },
  "Q4": {
    "summary": {
      "totalInvoices": 7282,
      "openInvoices": 3504,
      "clearedInvoices": 3778,
      "overdueInvoices": 1363,
      "totalOpenAR": 19064246906,
      "overdueAR": 4055144014,
      "currentAR": 15009102892,
      "totalSales": 38462994479
    },
    "executive": {
      "dso": {
        "overall": 44.6,
        "monthly": [
          {
            "month": "Jan'26",
            "value": 5.4
          },
          {
            "month": "Feb'26",
            "value": 16.7
          },
          {
            "month": "Mar'26",
            "value": 23
          }
        ]
      },
      "overdueRatio": {
        "overall": 21.3,
        "monthly": [
          {
            "month": "Jan'26",
            "value": 100
          },
          {
            "month": "Feb'26",
            "value": 20.2
          },
          {
            "month": "Mar'26",
            "value": 3.2
          }
        ]
      },
      "revenueAtRisk": {
        "value": 9.3
      },
      "receivablesTurnover": {
        "overall": 6.2,
        "monthly": [
          {
            "month": "Jan'26",
            "value": 6
          },
          {
            "month": "Feb'26",
            "value": 2.6
          },
          {
            "month": "Mar'26",
            "value": 1.6
          }
        ]
      },
      "netARMovement": {
        "monthly": [
          {
            "month": "Jan'26",
            "value": 276575373,
            "label": "Jan'26"
          },
          {
            "month": "Feb'26",
            "value": 3965516825,
            "label": "Feb'26"
          },
          {
            "month": "Mar'26",
            "value": 3815280789,
            "label": "Mar'26"
          }
        ]
      }
    },
    "collection": {
      "cei": {
        "overall": 88.8,
        "monthly": [
          {
            "month": "Jan'26",
            "value": 84.7
          },
          {
            "month": "Feb'26",
            "value": 85
          },
          {
            "month": "Mar'26",
            "value": 96.7
          }
        ]
      },
      "onTimePayment": {
        "weekly": [
          {
            "week": "W41",
            "value": 0
          },
          {
            "week": "W42",
            "value": 0
          },
          {
            "week": "W43",
            "value": 0
          },
          {
            "week": "W44",
            "value": 0
          },
          {
            "week": "W45",
            "value": 0
          },
          {
            "week": "W46",
            "value": 0
          },
          {
            "week": "W47",
            "value": 0
          },
          {
            "week": "W48",
            "value": 0
          },
          {
            "week": "W49",
            "value": 0
          },
          {
            "week": "W50",
            "value": 0
          },
          {
            "week": "W51",
            "value": 0
          },
          {
            "week": "W52",
            "value": 0
          }
        ]
      },
      "collectionEffectiveness": {
        "weekly": [
          {
            "week": "W41",
            "value": 0
          },
          {
            "week": "W42",
            "value": 0
          },
          {
            "week": "W43",
            "value": 0
          },
          {
            "week": "W44",
            "value": 0
          },
          {
            "week": "W45",
            "value": 0
          },
          {
            "week": "W46",
            "value": 0
          },
          {
            "week": "W47",
            "value": 0
          },
          {
            "week": "W48",
            "value": 0
          },
          {
            "week": "W49",
            "value": 0
          },
          {
            "week": "W50",
            "value": 0
          },
          {
            "week": "W51",
            "value": 0
          },
          {
            "week": "W52",
            "value": 0
          }
        ]
      },
      "creditPeriodEffectiveness": {
        "data": [
          {
            "creditPeriod": "7 days",
            "value": 73.3
          },
          {
            "creditPeriod": "15 days",
            "value": 70.3
          },
          {
            "creditPeriod": "30 days",
            "value": 71.3
          },
          {
            "creditPeriod": "45 days",
            "value": 73.9
          },
          {
            "creditPeriod": "60 days",
            "value": 74.3
          }
        ]
      }
    },
    "aging": {
      "buckets": [
        {
          "bucket": "Not Due",
          "key": "NOT_DUE",
          "count": 2141,
          "amount": 15009102892,
          "percentage": 78.7,
          "color": "#16a34a"
        },
        {
          "bucket": "1-7 days",
          "key": "1_7",
          "count": 284,
          "amount": 892211204,
          "percentage": 4.7,
          "color": "#22c55e"
        },
        {
          "bucket": "8-15 days",
          "key": "8_15",
          "count": 222,
          "amount": 633316612,
          "percentage": 3.3,
          "color": "#3b82f6"
        },
        {
          "bucket": "16-30 days",
          "key": "16_30",
          "count": 297,
          "amount": 1129024743,
          "percentage": 5.9,
          "color": "#eab308"
        },
        {
          "bucket": "31-45 days",
          "key": "31_45",
          "count": 238,
          "amount": 638091959,
          "percentage": 3.3,
          "color": "#d97706"
        },
        {
          "bucket": "46-60 days",
          "key": "46_60",
          "count": 215,
          "amount": 547837932,
          "percentage": 2.9,
          "color": "#ea580c"
        },
        {
          "bucket": "60+ days",
          "key": "60_PLUS",
          "count": 107,
          "amount": 214661563,
          "percentage": 1.1,
          "color": "#dc2626"
        }
      ],
      "overdueDensity": {
        "count": 38.9,
        "value": 21.3
      },
      "peakExposure": {
        "amount": 162846544,
        "invoiceNo": "2026009301",
        "companyCode": "2000",
        "daysOverdue": 23
      }
    },
    "operational": {
      "invoiceToCash": {
        "p50": 27,
        "p90": 55
      },
      "creditPeriodUtilization": {
        "overall": 119.5,
        "monthly": [
          {
            "month": "Jan'26",
            "value": 127.8
          },
          {
            "month": "Feb'26",
            "value": 117.8
          },
          {
            "month": "Mar'26",
            "value": 89.5
          }
        ]
      },
      "daysToClearBacklog": {
        "weekly": [
          {
            "week": "W41",
            "value": 930.4
          },
          {
            "week": "W42",
            "value": 0
          },
          {
            "week": "W43",
            "value": 999
          },
          {
            "week": "W44",
            "value": 0
          },
          {
            "week": "W45",
            "value": 0
          },
          {
            "week": "W46",
            "value": 18.1
          },
          {
            "week": "W47",
            "value": 200.4
          },
          {
            "week": "W48",
            "value": 13.3
          },
          {
            "week": "W49",
            "value": 999
          },
          {
            "week": "W50",
            "value": 999
          },
          {
            "week": "W51",
            "value": 999
          },
          {
            "week": "W52",
            "value": 34.3
          }
        ]
      }
    }
  },
  "All": {
    "summary": {
      "totalInvoices": 25000,
      "openInvoices": 7683,
      "clearedInvoices": 17317,
      "overdueInvoices": 5542,
      "totalOpenAR": 34218921368,
      "overdueAR": 19209818476,
      "currentAR": 15009102892,
      "totalSales": 129123080799
    },
    "executive": {
      "dso": {
        "overall": 96.7,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 4.9
          },
          {
            "month": "May'25",
            "value": 6
          },
          {
            "month": "Jun'25",
            "value": 4.3
          },
          {
            "month": "Jul'25",
            "value": 4.6
          },
          {
            "month": "Aug'25",
            "value": 4.9
          },
          {
            "month": "Sep'25",
            "value": 4.5
          },
          {
            "month": "Oct'25",
            "value": 5.5
          },
          {
            "month": "Nov'25",
            "value": 5.2
          },
          {
            "month": "Dec'25",
            "value": 5.2
          },
          {
            "month": "Jan'26",
            "value": 5.4
          },
          {
            "month": "Feb'26",
            "value": 16.7
          },
          {
            "month": "Mar'26",
            "value": 23
          }
        ]
      },
      "overdueRatio": {
        "overall": 56.1,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 100
          },
          {
            "month": "May'25",
            "value": 100
          },
          {
            "month": "Jun'25",
            "value": 100
          },
          {
            "month": "Jul'25",
            "value": 100
          },
          {
            "month": "Aug'25",
            "value": 100
          },
          {
            "month": "Sep'25",
            "value": 100
          },
          {
            "month": "Oct'25",
            "value": 100
          },
          {
            "month": "Nov'25",
            "value": 100
          },
          {
            "month": "Dec'25",
            "value": 100
          },
          {
            "month": "Jan'26",
            "value": 100
          },
          {
            "month": "Feb'26",
            "value": 20.2
          },
          {
            "month": "Mar'26",
            "value": 3.2
          }
        ]
      },
      "revenueAtRisk": {
        "value": 27.2
      },
      "receivablesTurnover": {
        "overall": 25.3,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 12.5
          },
          {
            "month": "May'25",
            "value": 5.7
          },
          {
            "month": "Jun'25",
            "value": 6.4
          },
          {
            "month": "Jul'25",
            "value": 7.1
          },
          {
            "month": "Aug'25",
            "value": 6.9
          },
          {
            "month": "Sep'25",
            "value": 6.1
          },
          {
            "month": "Oct'25",
            "value": 6.6
          },
          {
            "month": "Nov'25",
            "value": 5.6
          },
          {
            "month": "Dec'25",
            "value": 6.1
          },
          {
            "month": "Jan'26",
            "value": 6
          },
          {
            "month": "Feb'26",
            "value": 2.6
          },
          {
            "month": "Mar'26",
            "value": 1.6
          }
        ]
      },
      "netARMovement": {
        "monthly": [
          {
            "month": "Apr'25",
            "value": 1310684907,
            "label": "Apr'25"
          },
          {
            "month": "May'25",
            "value": 255256859,
            "label": "May'25"
          },
          {
            "month": "Jun'25",
            "value": -298261264,
            "label": "Jun'25"
          },
          {
            "month": "Jul'25",
            "value": 270788123,
            "label": "Jul'25"
          },
          {
            "month": "Aug'25",
            "value": 251373597,
            "label": "Aug'25"
          },
          {
            "month": "Sep'25",
            "value": -287264807,
            "label": "Sep'25"
          },
          {
            "month": "Oct'25",
            "value": 577272108,
            "label": "Oct'25"
          },
          {
            "month": "Nov'25",
            "value": -142955471,
            "label": "Nov'25"
          },
          {
            "month": "Dec'25",
            "value": 225841396,
            "label": "Dec'25"
          },
          {
            "month": "Jan'26",
            "value": 276575373,
            "label": "Jan'26"
          },
          {
            "month": "Feb'26",
            "value": 3965516825,
            "label": "Feb'26"
          },
          {
            "month": "Mar'26",
            "value": 3815280789,
            "label": "Mar'26"
          }
        ]
      }
    },
    "collection": {
      "cei": {
        "overall": 86.1,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 83.7
          },
          {
            "month": "May'25",
            "value": 83.2
          },
          {
            "month": "Jun'25",
            "value": 87.8
          },
          {
            "month": "Jul'25",
            "value": 86
          },
          {
            "month": "Aug'25",
            "value": 85.5
          },
          {
            "month": "Sep'25",
            "value": 87.3
          },
          {
            "month": "Oct'25",
            "value": 83.7
          },
          {
            "month": "Nov'25",
            "value": 85.3
          },
          {
            "month": "Dec'25",
            "value": 84.9
          },
          {
            "month": "Jan'26",
            "value": 84.7
          },
          {
            "month": "Feb'26",
            "value": 85
          },
          {
            "month": "Mar'26",
            "value": 96.7
          }
        ]
      },
      "onTimePayment": {
        "weekly": [
          {
            "week": "W1",
            "value": 0
          },
          {
            "week": "W2",
            "value": 0
          },
          {
            "week": "W3",
            "value": 0
          },
          {
            "week": "W4",
            "value": 0
          },
          {
            "week": "W5",
            "value": 0
          },
          {
            "week": "W6",
            "value": 0
          },
          {
            "week": "W7",
            "value": 0
          },
          {
            "week": "W8",
            "value": 0
          },
          {
            "week": "W9",
            "value": 0
          },
          {
            "week": "W10",
            "value": 0
          },
          {
            "week": "W11",
            "value": 0
          },
          {
            "week": "W12",
            "value": 0
          },
          {
            "week": "W13",
            "value": 0
          },
          {
            "week": "W14",
            "value": 0
          },
          {
            "week": "W15",
            "value": 0
          },
          {
            "week": "W16",
            "value": 0
          },
          {
            "week": "W17",
            "value": 0
          },
          {
            "week": "W18",
            "value": 0
          },
          {
            "week": "W19",
            "value": 0
          },
          {
            "week": "W20",
            "value": 0
          },
          {
            "week": "W21",
            "value": 0
          },
          {
            "week": "W22",
            "value": 0
          },
          {
            "week": "W23",
            "value": 0
          },
          {
            "week": "W24",
            "value": 0
          },
          {
            "week": "W25",
            "value": 0
          },
          {
            "week": "W26",
            "value": 0
          },
          {
            "week": "W27",
            "value": 0
          },
          {
            "week": "W28",
            "value": 0
          },
          {
            "week": "W29",
            "value": 0
          },
          {
            "week": "W30",
            "value": 0
          },
          {
            "week": "W31",
            "value": 0
          },
          {
            "week": "W32",
            "value": 0
          },
          {
            "week": "W33",
            "value": 0
          },
          {
            "week": "W34",
            "value": 0
          },
          {
            "week": "W35",
            "value": 0
          },
          {
            "week": "W36",
            "value": 0
          },
          {
            "week": "W37",
            "value": 0
          },
          {
            "week": "W38",
            "value": 0
          },
          {
            "week": "W39",
            "value": 0
          },
          {
            "week": "W40",
            "value": 0
          },
          {
            "week": "W41",
            "value": 0
          },
          {
            "week": "W42",
            "value": 0
          },
          {
            "week": "W43",
            "value": 0
          },
          {
            "week": "W44",
            "value": 0
          },
          {
            "week": "W45",
            "value": 0
          },
          {
            "week": "W46",
            "value": 0
          },
          {
            "week": "W47",
            "value": 0
          },
          {
            "week": "W48",
            "value": 0
          },
          {
            "week": "W49",
            "value": 0
          },
          {
            "week": "W50",
            "value": 0
          },
          {
            "week": "W51",
            "value": 0
          },
          {
            "week": "W52",
            "value": 0
          }
        ]
      },
      "collectionEffectiveness": {
        "weekly": [
          {
            "week": "W1",
            "value": 0
          },
          {
            "week": "W2",
            "value": 0
          },
          {
            "week": "W3",
            "value": 0
          },
          {
            "week": "W4",
            "value": 0
          },
          {
            "week": "W5",
            "value": 0
          },
          {
            "week": "W6",
            "value": 0
          },
          {
            "week": "W7",
            "value": 0
          },
          {
            "week": "W8",
            "value": 0
          },
          {
            "week": "W9",
            "value": 0
          },
          {
            "week": "W10",
            "value": 0
          },
          {
            "week": "W11",
            "value": 0
          },
          {
            "week": "W12",
            "value": 0
          },
          {
            "week": "W13",
            "value": 0
          },
          {
            "week": "W14",
            "value": 0
          },
          {
            "week": "W15",
            "value": 0
          },
          {
            "week": "W16",
            "value": 0
          },
          {
            "week": "W17",
            "value": 0
          },
          {
            "week": "W18",
            "value": 0
          },
          {
            "week": "W19",
            "value": 0
          },
          {
            "week": "W20",
            "value": 0
          },
          {
            "week": "W21",
            "value": 0
          },
          {
            "week": "W22",
            "value": 0
          },
          {
            "week": "W23",
            "value": 0
          },
          {
            "week": "W24",
            "value": 0
          },
          {
            "week": "W25",
            "value": 0
          },
          {
            "week": "W26",
            "value": 0
          },
          {
            "week": "W27",
            "value": 0
          },
          {
            "week": "W28",
            "value": 0
          },
          {
            "week": "W29",
            "value": 0
          },
          {
            "week": "W30",
            "value": 0
          },
          {
            "week": "W31",
            "value": 0
          },
          {
            "week": "W32",
            "value": 0
          },
          {
            "week": "W33",
            "value": 0
          },
          {
            "week": "W34",
            "value": 0
          },
          {
            "week": "W35",
            "value": 0
          },
          {
            "week": "W36",
            "value": 0
          },
          {
            "week": "W37",
            "value": 0
          },
          {
            "week": "W38",
            "value": 0
          },
          {
            "week": "W39",
            "value": 0
          },
          {
            "week": "W40",
            "value": 0
          },
          {
            "week": "W41",
            "value": 0
          },
          {
            "week": "W42",
            "value": 0
          },
          {
            "week": "W43",
            "value": 0
          },
          {
            "week": "W44",
            "value": 0
          },
          {
            "week": "W45",
            "value": 0
          },
          {
            "week": "W46",
            "value": 0
          },
          {
            "week": "W47",
            "value": 0
          },
          {
            "week": "W48",
            "value": 0
          },
          {
            "week": "W49",
            "value": 0
          },
          {
            "week": "W50",
            "value": 0
          },
          {
            "week": "W51",
            "value": 0
          },
          {
            "week": "W52",
            "value": 0
          }
        ]
      },
      "creditPeriodEffectiveness": {
        "data": [
          {
            "creditPeriod": "7 days",
            "value": 71
          },
          {
            "creditPeriod": "15 days",
            "value": 64.7
          },
          {
            "creditPeriod": "30 days",
            "value": 70.6
          },
          {
            "creditPeriod": "45 days",
            "value": 79.5
          },
          {
            "creditPeriod": "60 days",
            "value": 78.5
          }
        ]
      }
    },
    "aging": {
      "buckets": [
        {
          "bucket": "Not Due",
          "key": "NOT_DUE",
          "count": 2141,
          "amount": 15009102892,
          "percentage": 43.9,
          "color": "#16a34a"
        },
        {
          "bucket": "1-7 days",
          "key": "1_7",
          "count": 284,
          "amount": 892211204,
          "percentage": 2.6,
          "color": "#22c55e"
        },
        {
          "bucket": "8-15 days",
          "key": "8_15",
          "count": 222,
          "amount": 633316612,
          "percentage": 1.9,
          "color": "#3b82f6"
        },
        {
          "bucket": "16-30 days",
          "key": "16_30",
          "count": 297,
          "amount": 1129024743,
          "percentage": 3.3,
          "color": "#eab308"
        },
        {
          "bucket": "31-45 days",
          "key": "31_45",
          "count": 255,
          "amount": 794472995,
          "percentage": 2.3,
          "color": "#d97706"
        },
        {
          "bucket": "46-60 days",
          "key": "46_60",
          "count": 302,
          "amount": 1296733606,
          "percentage": 3.8,
          "color": "#ea580c"
        },
        {
          "bucket": "60+ days",
          "key": "60_PLUS",
          "count": 4182,
          "amount": 14464059316,
          "percentage": 42.3,
          "color": "#dc2626"
        }
      ],
      "overdueDensity": {
        "count": 72.1,
        "value": 56.1
      },
      "peakExposure": {
        "amount": 168769906,
        "invoiceNo": "2025006542",
        "companyCode": "3000",
        "daysOverdue": 170
      }
    },
    "operational": {
      "invoiceToCash": {
        "p50": 36,
        "p90": 62
      },
      "creditPeriodUtilization": {
        "overall": 129.3,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 135.4
          },
          {
            "month": "May'25",
            "value": 131.4
          },
          {
            "month": "Jun'25",
            "value": 132.6
          },
          {
            "month": "Jul'25",
            "value": 132.9
          },
          {
            "month": "Aug'25",
            "value": 130.8
          },
          {
            "month": "Sep'25",
            "value": 127.3
          },
          {
            "month": "Oct'25",
            "value": 132.5
          },
          {
            "month": "Nov'25",
            "value": 135.7
          },
          {
            "month": "Dec'25",
            "value": 129.3
          },
          {
            "month": "Jan'26",
            "value": 127.8
          },
          {
            "month": "Feb'26",
            "value": 117.8
          },
          {
            "month": "Mar'26",
            "value": 89.5
          }
        ]
      },
      "daysToClearBacklog": {
        "weekly": [
          {
            "week": "W1",
            "value": 0
          },
          {
            "week": "W2",
            "value": 0
          },
          {
            "week": "W3",
            "value": 0
          },
          {
            "week": "W4",
            "value": 0
          },
          {
            "week": "W5",
            "value": 0
          },
          {
            "week": "W6",
            "value": 0
          },
          {
            "week": "W7",
            "value": 0
          },
          {
            "week": "W8",
            "value": 0
          },
          {
            "week": "W9",
            "value": 0
          },
          {
            "week": "W10",
            "value": 0
          },
          {
            "week": "W11",
            "value": 0
          },
          {
            "week": "W12",
            "value": 0
          },
          {
            "week": "W13",
            "value": 0
          },
          {
            "week": "W14",
            "value": 71.8
          },
          {
            "week": "W15",
            "value": 190.9
          },
          {
            "week": "W16",
            "value": 20.7
          },
          {
            "week": "W17",
            "value": 85.3
          },
          {
            "week": "W18",
            "value": 78.1
          },
          {
            "week": "W19",
            "value": 0
          },
          {
            "week": "W20",
            "value": 39.5
          },
          {
            "week": "W21",
            "value": 430.3
          },
          {
            "week": "W22",
            "value": 0
          },
          {
            "week": "W23",
            "value": 999
          },
          {
            "week": "W24",
            "value": 471.6
          },
          {
            "week": "W25",
            "value": 0
          },
          {
            "week": "W26",
            "value": 22
          },
          {
            "week": "W27",
            "value": 12
          },
          {
            "week": "W28",
            "value": 384.1
          },
          {
            "week": "W29",
            "value": 999
          },
          {
            "week": "W30",
            "value": 705
          },
          {
            "week": "W31",
            "value": 999
          },
          {
            "week": "W32",
            "value": 430.4
          },
          {
            "week": "W33",
            "value": 999
          },
          {
            "week": "W34",
            "value": 762.2
          },
          {
            "week": "W35",
            "value": 999
          },
          {
            "week": "W36",
            "value": 999
          },
          {
            "week": "W37",
            "value": 40.5
          },
          {
            "week": "W38",
            "value": 999
          },
          {
            "week": "W39",
            "value": 999
          },
          {
            "week": "W40",
            "value": 88.6
          },
          {
            "week": "W41",
            "value": 930.4
          },
          {
            "week": "W42",
            "value": 0
          },
          {
            "week": "W43",
            "value": 999
          },
          {
            "week": "W44",
            "value": 0
          },
          {
            "week": "W45",
            "value": 0
          },
          {
            "week": "W46",
            "value": 18.1
          },
          {
            "week": "W47",
            "value": 200.4
          },
          {
            "week": "W48",
            "value": 13.3
          },
          {
            "week": "W49",
            "value": 999
          },
          {
            "week": "W50",
            "value": 999
          },
          {
            "week": "W51",
            "value": 999
          },
          {
            "week": "W52",
            "value": 34.3
          }
        ]
      }
    }
  }
} as any;
