// ============================================================
// PRE-COMPUTED KPI DATA — Generated from 25,000-invoice SQLite DB
// Auto-generated by prisma/compute-dashboard-data.ts
// DO NOT EDIT MANUALLY — re-run the compute script to update
// ============================================================

export type QuarterKey = "Q1" | "Q2" | "Q3" | "Q4" | "All";

export interface AgingBucket {
  bucket: string;
  key: string;
  count: number;
  amount: number;
  percentage: number;
  color: string;
}

export interface MonthlyPoint {
  month: string;
  value: number;
}

export interface WeeklyPoint {
  week: string;
  value: number;
}

export interface WaterfallPoint {
  month: string;
  value: number;
  label: string;
}

export interface DSOBridgeSegment {
  segment: string;
  dso: number;
  weight: number;
  contribution: number;
}

export interface HealthScoreComponents {
  DSO: number;
  CEI: number;
  Overdue: number;
  Aging: number;
  Concentration: number;
  Trend: number;
}

export interface CompanyCodePerf {
  code: string;
  name: string;
  dso: number;
  overdueRatio: number;
  openAR: number;
  invoiceCount: number;
}

export interface SegmentEfficiency {
  segment: string;
  dso: number;
  collectionRate: number;
  overdueRatio: number;
  efficiencyScore: number;
}

export interface AdvancedKPIs {
  dsoBridge: {
    blendedDSO: number;
    segments: DSOBridgeSegment[];
  };
  arHealthScore: {
    score: number;
    grade: string;
    components: HealthScoreComponents;
  };
  termsMixDrag: {
    weightedAvgTerms: number;
    avgActualPayDays: number;
    drag: number;
  };
  carryingCost: {
    dailyCost: number;
    monthlyCost: number;
    annualCost: number;
    avgDaysOutstanding: number;
  };
  cashFlowLeakage: {
    bestPossibleDSO: number;
    actualDSO: number;
    leakageDays: number;
    leakageINR: number;
  };
  companyCodePerformance: CompanyCodePerf[];
  segmentEfficiency: SegmentEfficiency[];
}

export interface QuarterData {
  summary: {
    totalInvoices: number;
    openInvoices: number;
    clearedInvoices: number;
    overdueInvoices: number;
    totalOpenAR: number;
    overdueAR: number;
    currentAR: number;
    totalSales: number;
  };
  executive: {
    dso: { overall: number; monthly: MonthlyPoint[] };
    overdueRatio: { overall: number; monthly: MonthlyPoint[] };
    revenueAtRisk: { value: number };
    receivablesTurnover: { overall: number; monthly: MonthlyPoint[] };
    netARMovement: { monthly: WaterfallPoint[] };
  };
  collection: {
    cei: { overall: number; monthly: MonthlyPoint[] };
    onTimePayment: { weekly: WeeklyPoint[] };
    collectionEffectiveness: { weekly: WeeklyPoint[] };
    creditPeriodEffectiveness: { data: { creditPeriod: string; value: number }[] };
  };
  aging: {
    buckets: AgingBucket[];
    overdueDensity: { count: number; value: number };
    peakExposure: { amount: number; invoiceNo: string; companyCode: string; daysOverdue: number };
  };
  operational: {
    invoiceToCash: { p50: number; p90: number };
    creditPeriodUtilization: { overall: number; monthly: MonthlyPoint[] };
    daysToClearBacklog: { weekly: WeeklyPoint[] };
  };
  advanced: AdvancedKPIs;
}

export const COMPUTED_KPI_DATA: Record<QuarterKey, QuarterData> = {
  "Q1": {
    "summary": {
      "totalInvoices": 5123,
      "openInvoices": 1228,
      "clearedInvoices": 3895,
      "overdueInvoices": 1228,
      "totalOpenAR": 4144307176,
      "overdueAR": 4144307176,
      "currentAR": 0,
      "totalSales": 24812764880
    },
    "executive": {
      "dso": {
        "overall": 15,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 4.9
          },
          {
            "month": "May'25",
            "value": 6
          },
          {
            "month": "Jun'25",
            "value": 4.3
          }
        ]
      },
      "overdueRatio": {
        "overall": 100,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 100
          },
          {
            "month": "May'25",
            "value": 100
          },
          {
            "month": "Jun'25",
            "value": 100
          }
        ]
      },
      "revenueAtRisk": {
        "value": 50.7
      },
      "receivablesTurnover": {
        "overall": 39.1,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 12.5
          },
          {
            "month": "May'25",
            "value": 5.7
          },
          {
            "month": "Jun'25",
            "value": 6.4
          }
        ]
      },
      "netARMovement": {
        "monthly": [
          {
            "month": "Apr'25",
            "value": 1310684907,
            "label": "Apr'25"
          },
          {
            "month": "May'25",
            "value": 255256859,
            "label": "May'25"
          },
          {
            "month": "Jun'25",
            "value": -298261264,
            "label": "Jun'25"
          }
        ]
      }
    },
    "collection": {
      "cei": {
        "overall": 84.9,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 83.7
          },
          {
            "month": "May'25",
            "value": 83.2
          },
          {
            "month": "Jun'25",
            "value": 87.8
          }
        ]
      },
      "onTimePayment": {
        "weekly": [
          {
            "week": "W1",
            "value": 0
          },
          {
            "week": "W2",
            "value": 0
          },
          {
            "week": "W3",
            "value": 0
          },
          {
            "week": "W4",
            "value": 0
          },
          {
            "week": "W5",
            "value": 0
          },
          {
            "week": "W6",
            "value": 0
          },
          {
            "week": "W7",
            "value": 0
          },
          {
            "week": "W8",
            "value": 0
          },
          {
            "week": "W9",
            "value": 0
          },
          {
            "week": "W10",
            "value": 0
          },
          {
            "week": "W11",
            "value": 0
          },
          {
            "week": "W12",
            "value": 0
          },
          {
            "week": "W13",
            "value": 0
          }
        ]
      },
      "collectionEffectiveness": {
        "weekly": [
          {
            "week": "W1",
            "value": 0
          },
          {
            "week": "W2",
            "value": 0
          },
          {
            "week": "W3",
            "value": 0
          },
          {
            "week": "W4",
            "value": 0
          },
          {
            "week": "W5",
            "value": 0
          },
          {
            "week": "W6",
            "value": 0
          },
          {
            "week": "W7",
            "value": 0
          },
          {
            "week": "W8",
            "value": 0
          },
          {
            "week": "W9",
            "value": 0
          },
          {
            "week": "W10",
            "value": 0
          },
          {
            "week": "W11",
            "value": 0
          },
          {
            "week": "W12",
            "value": 0
          },
          {
            "week": "W13",
            "value": 0
          }
        ]
      },
      "creditPeriodEffectiveness": {
        "data": [
          {
            "creditPeriod": "7 days",
            "value": 61.3
          },
          {
            "creditPeriod": "15 days",
            "value": 66.6
          },
          {
            "creditPeriod": "30 days",
            "value": 70.4
          },
          {
            "creditPeriod": "45 days",
            "value": 75.7
          },
          {
            "creditPeriod": "60 days",
            "value": 79.8
          }
        ]
      }
    },
    "aging": {
      "buckets": [
        {
          "bucket": "Not Due",
          "key": "NOT_DUE",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#16a34a"
        },
        {
          "bucket": "1-7 days",
          "key": "1_7",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#22c55e"
        },
        {
          "bucket": "8-15 days",
          "key": "8_15",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#3b82f6"
        },
        {
          "bucket": "16-30 days",
          "key": "16_30",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#eab308"
        },
        {
          "bucket": "31-45 days",
          "key": "31_45",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#d97706"
        },
        {
          "bucket": "46-60 days",
          "key": "46_60",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#ea580c"
        },
        {
          "bucket": "60+ days",
          "key": "60_PLUS",
          "count": 1228,
          "amount": 4144307176,
          "percentage": 100,
          "color": "#dc2626"
        }
      ],
      "overdueDensity": {
        "count": 100,
        "value": 100
      },
      "peakExposure": {
        "amount": 140506925,
        "invoiceNo": "2025012738",
        "companyCode": "2000",
        "daysOverdue": 229
      }
    },
    "operational": {
      "invoiceToCash": {
        "p50": 37,
        "p90": 64
      },
      "creditPeriodUtilization": {
        "overall": 133.1,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 135.4
          },
          {
            "month": "May'25",
            "value": 131.4
          },
          {
            "month": "Jun'25",
            "value": 132.6
          }
        ]
      },
      "daysToClearBacklog": {
        "weekly": [
          {
            "week": "W1",
            "value": 0
          },
          {
            "week": "W2",
            "value": 0
          },
          {
            "week": "W3",
            "value": 0
          },
          {
            "week": "W4",
            "value": 0
          },
          {
            "week": "W5",
            "value": 0
          },
          {
            "week": "W6",
            "value": 0
          },
          {
            "week": "W7",
            "value": 0
          },
          {
            "week": "W8",
            "value": 0
          },
          {
            "week": "W9",
            "value": 0
          },
          {
            "week": "W10",
            "value": 0
          },
          {
            "week": "W11",
            "value": 0
          },
          {
            "week": "W12",
            "value": 0
          },
          {
            "week": "W13",
            "value": 0
          }
        ]
      }
    },
    "advanced": {
      "dsoBridge": {
        "blendedDSO": 15,
        "segments": [
          {
            "segment": "STRATEGIC",
            "dso": 6,
            "weight": 31,
            "contribution": -2.8
          },
          {
            "segment": "KEY",
            "dso": 16.2,
            "weight": 39.9,
            "contribution": 0.5
          },
          {
            "segment": "STANDARD",
            "dso": 21.1,
            "weight": 18.5,
            "contribution": 1.1
          },
          {
            "segment": "SMB",
            "dso": 26.4,
            "weight": 10.5,
            "contribution": 1.2
          }
        ]
      },
      "arHealthScore": {
        "score": 56,
        "grade": "C",
        "components": {
          "DSO": 100,
          "CEI": 85,
          "Overdue": 0,
          "Aging": 0,
          "Concentration": 71,
          "Trend": 53
        }
      },
      "termsMixDrag": {
        "weightedAvgTerms": 36.8,
        "avgActualPayDays": 37,
        "drag": 0.2
      },
      "carryingCost": {
        "dailyCost": 1135427,
        "monthlyCost": 34062799,
        "annualCost": 364289797,
        "avgDaysOutstanding": 321
      },
      "cashFlowLeakage": {
        "bestPossibleDSO": 36.8,
        "actualDSO": 15,
        "leakageDays": -21.8,
        "leakageINR": -6006381742
      },
      "companyCodePerformance": [
        {
          "code": "1000",
          "name": "HQ Operations India",
          "dso": 13.7,
          "overdueRatio": 100,
          "openAR": 1277267249,
          "invoiceCount": 414
        },
        {
          "code": "2000",
          "name": "Manufacturing Division",
          "dso": 13.9,
          "overdueRatio": 100,
          "openAR": 1273419626,
          "invoiceCount": 384
        },
        {
          "code": "3000",
          "name": "Services & Solutions",
          "dso": 17.5,
          "overdueRatio": 100,
          "openAR": 1593620301,
          "invoiceCount": 430
        }
      ],
      "segmentEfficiency": [
        {
          "segment": "STRATEGIC",
          "dso": 6,
          "collectionRate": 93.3,
          "overdueRatio": 100,
          "efficiencyScore": 0
        },
        {
          "segment": "KEY",
          "dso": 16.2,
          "collectionRate": 82,
          "overdueRatio": 100,
          "efficiencyScore": 0
        },
        {
          "segment": "STANDARD",
          "dso": 21.1,
          "collectionRate": 76.6,
          "overdueRatio": 100,
          "efficiencyScore": 0
        },
        {
          "segment": "SMB",
          "dso": 26.4,
          "collectionRate": 70.6,
          "overdueRatio": 100,
          "efficiencyScore": 0
        }
      ]
    }
  },
  "Q2": {
    "summary": {
      "totalInvoices": 6083,
      "openInvoices": 1380,
      "clearedInvoices": 4703,
      "overdueInvoices": 1380,
      "totalOpenAR": 4830888263,
      "overdueAR": 4830888263,
      "currentAR": 0,
      "totalSales": 30866070569
    },
    "executive": {
      "dso": {
        "overall": 14.1,
        "monthly": [
          {
            "month": "Jul'25",
            "value": 4.6
          },
          {
            "month": "Aug'25",
            "value": 4.9
          },
          {
            "month": "Sep'25",
            "value": 4.5
          }
        ]
      },
      "overdueRatio": {
        "overall": 100,
        "monthly": [
          {
            "month": "Jul'25",
            "value": 100
          },
          {
            "month": "Aug'25",
            "value": 100
          },
          {
            "month": "Sep'25",
            "value": 100
          }
        ]
      },
      "revenueAtRisk": {
        "value": 48.6
      },
      "receivablesTurnover": {
        "overall": 22.3,
        "monthly": [
          {
            "month": "Jul'25",
            "value": 7.1
          },
          {
            "month": "Aug'25",
            "value": 6.9
          },
          {
            "month": "Sep'25",
            "value": 6.1
          }
        ]
      },
      "netARMovement": {
        "monthly": [
          {
            "month": "Jul'25",
            "value": 270788123,
            "label": "Jul'25"
          },
          {
            "month": "Aug'25",
            "value": 251373597,
            "label": "Aug'25"
          },
          {
            "month": "Sep'25",
            "value": -287264807,
            "label": "Sep'25"
          }
        ]
      }
    },
    "collection": {
      "cei": {
        "overall": 86.3,
        "monthly": [
          {
            "month": "Jul'25",
            "value": 86
          },
          {
            "month": "Aug'25",
            "value": 85.5
          },
          {
            "month": "Sep'25",
            "value": 87.3
          }
        ]
      },
      "onTimePayment": {
        "weekly": [
          {
            "week": "W14",
            "value": 0
          },
          {
            "week": "W15",
            "value": 0
          },
          {
            "week": "W16",
            "value": 0
          },
          {
            "week": "W17",
            "value": 0
          },
          {
            "week": "W18",
            "value": 0
          },
          {
            "week": "W19",
            "value": 0
          },
          {
            "week": "W20",
            "value": 0
          },
          {
            "week": "W21",
            "value": 0
          },
          {
            "week": "W22",
            "value": 0
          },
          {
            "week": "W23",
            "value": 0
          },
          {
            "week": "W24",
            "value": 0
          },
          {
            "week": "W25",
            "value": 0
          },
          {
            "week": "W26",
            "value": 0
          },
          {
            "week": "W27",
            "value": 0
          }
        ]
      },
      "collectionEffectiveness": {
        "weekly": [
          {
            "week": "W14",
            "value": 0
          },
          {
            "week": "W15",
            "value": 0
          },
          {
            "week": "W16",
            "value": 0
          },
          {
            "week": "W17",
            "value": 0
          },
          {
            "week": "W18",
            "value": 0
          },
          {
            "week": "W19",
            "value": 0
          },
          {
            "week": "W20",
            "value": 0
          },
          {
            "week": "W21",
            "value": 0
          },
          {
            "week": "W22",
            "value": 0
          },
          {
            "week": "W23",
            "value": 0
          },
          {
            "week": "W24",
            "value": 0
          },
          {
            "week": "W25",
            "value": 0
          },
          {
            "week": "W26",
            "value": 0
          },
          {
            "week": "W27",
            "value": 0
          }
        ]
      },
      "creditPeriodEffectiveness": {
        "data": [
          {
            "creditPeriod": "7 days",
            "value": 67.2
          },
          {
            "creditPeriod": "15 days",
            "value": 58.8
          },
          {
            "creditPeriod": "30 days",
            "value": 72
          },
          {
            "creditPeriod": "45 days",
            "value": 81.9
          },
          {
            "creditPeriod": "60 days",
            "value": 78.9
          }
        ]
      }
    },
    "aging": {
      "buckets": [
        {
          "bucket": "Not Due",
          "key": "NOT_DUE",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#16a34a"
        },
        {
          "bucket": "1-7 days",
          "key": "1_7",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#22c55e"
        },
        {
          "bucket": "8-15 days",
          "key": "8_15",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#3b82f6"
        },
        {
          "bucket": "16-30 days",
          "key": "16_30",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#eab308"
        },
        {
          "bucket": "31-45 days",
          "key": "31_45",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#d97706"
        },
        {
          "bucket": "46-60 days",
          "key": "46_60",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#ea580c"
        },
        {
          "bucket": "60+ days",
          "key": "60_PLUS",
          "count": 1380,
          "amount": 4830888263,
          "percentage": 100,
          "color": "#dc2626"
        }
      ],
      "overdueDensity": {
        "count": 100,
        "value": 100
      },
      "peakExposure": {
        "amount": 119333242,
        "invoiceNo": "2025022453",
        "companyCode": "3000",
        "daysOverdue": 203
      }
    },
    "operational": {
      "invoiceToCash": {
        "p50": 37,
        "p90": 64
      },
      "creditPeriodUtilization": {
        "overall": 130.3,
        "monthly": [
          {
            "month": "Jul'25",
            "value": 132.9
          },
          {
            "month": "Aug'25",
            "value": 130.8
          },
          {
            "month": "Sep'25",
            "value": 127.3
          }
        ]
      },
      "daysToClearBacklog": {
        "weekly": [
          {
            "week": "W14",
            "value": 71.8
          },
          {
            "week": "W15",
            "value": 190.9
          },
          {
            "week": "W16",
            "value": 20.7
          },
          {
            "week": "W17",
            "value": 85.3
          },
          {
            "week": "W18",
            "value": 78.1
          },
          {
            "week": "W19",
            "value": 0
          },
          {
            "week": "W20",
            "value": 39.5
          },
          {
            "week": "W21",
            "value": 430.3
          },
          {
            "week": "W22",
            "value": 0
          },
          {
            "week": "W23",
            "value": 999
          },
          {
            "week": "W24",
            "value": 471.6
          },
          {
            "week": "W25",
            "value": 0
          },
          {
            "week": "W26",
            "value": 22
          },
          {
            "week": "W27",
            "value": 12
          }
        ]
      }
    },
    "advanced": {
      "dsoBridge": {
        "blendedDSO": 14.1,
        "segments": [
          {
            "segment": "STRATEGIC",
            "dso": 7.4,
            "weight": 34.9,
            "contribution": -2.3
          },
          {
            "segment": "KEY",
            "dso": 13.6,
            "weight": 38.1,
            "contribution": -0.2
          },
          {
            "segment": "STANDARD",
            "dso": 21.8,
            "weight": 17.5,
            "contribution": 1.4
          },
          {
            "segment": "SMB",
            "dso": 26.5,
            "weight": 9.4,
            "contribution": 1.2
          }
        ]
      },
      "arHealthScore": {
        "score": 55,
        "grade": "C",
        "components": {
          "DSO": 100,
          "CEI": 86,
          "Overdue": 0,
          "Aging": 0,
          "Concentration": 70,
          "Trend": 51
        }
      },
      "termsMixDrag": {
        "weightedAvgTerms": 36,
        "avgActualPayDays": 37.1,
        "drag": 1.2
      },
      "carryingCost": {
        "dailyCost": 1323531,
        "monthlyCost": 39705931,
        "annualCost": 303234386,
        "avgDaysOutstanding": 229
      },
      "cashFlowLeakage": {
        "bestPossibleDSO": 36,
        "actualDSO": 14.1,
        "leakageDays": -21.9,
        "leakageINR": -7513623533
      },
      "companyCodePerformance": [
        {
          "code": "1000",
          "name": "HQ Operations India",
          "dso": 13.7,
          "overdueRatio": 100,
          "openAR": 1552508056,
          "invoiceCount": 451
        },
        {
          "code": "2000",
          "name": "Manufacturing Division",
          "dso": 11.1,
          "overdueRatio": 100,
          "openAR": 1330026417,
          "invoiceCount": 456
        },
        {
          "code": "3000",
          "name": "Services & Solutions",
          "dso": 17.7,
          "overdueRatio": 100,
          "openAR": 1948353790,
          "invoiceCount": 473
        }
      ],
      "segmentEfficiency": [
        {
          "segment": "STRATEGIC",
          "dso": 7.4,
          "collectionRate": 91.7,
          "overdueRatio": 100,
          "efficiencyScore": 0
        },
        {
          "segment": "KEY",
          "dso": 13.6,
          "collectionRate": 84.9,
          "overdueRatio": 100,
          "efficiencyScore": 0
        },
        {
          "segment": "STANDARD",
          "dso": 21.8,
          "collectionRate": 75.7,
          "overdueRatio": 100,
          "efficiencyScore": 0
        },
        {
          "segment": "SMB",
          "dso": 26.5,
          "collectionRate": 70.6,
          "overdueRatio": 100,
          "efficiencyScore": 0
        }
      ]
    }
  },
  "Q3": {
    "summary": {
      "totalInvoices": 6512,
      "openInvoices": 1571,
      "clearedInvoices": 4941,
      "overdueInvoices": 1571,
      "totalOpenAR": 6179479025,
      "overdueAR": 6179479025,
      "currentAR": 0,
      "totalSales": 34981250870
    },
    "executive": {
      "dso": {
        "overall": 15.9,
        "monthly": [
          {
            "month": "Oct'25",
            "value": 5.5
          },
          {
            "month": "Nov'25",
            "value": 5.2
          },
          {
            "month": "Dec'25",
            "value": 5.2
          }
        ]
      },
      "overdueRatio": {
        "overall": 100,
        "monthly": [
          {
            "month": "Oct'25",
            "value": 100
          },
          {
            "month": "Nov'25",
            "value": 100
          },
          {
            "month": "Dec'25",
            "value": 100
          }
        ]
      },
      "revenueAtRisk": {
        "value": 50.1
      },
      "receivablesTurnover": {
        "overall": 19.1,
        "monthly": [
          {
            "month": "Oct'25",
            "value": 6.6
          },
          {
            "month": "Nov'25",
            "value": 5.6
          },
          {
            "month": "Dec'25",
            "value": 6.1
          }
        ]
      },
      "netARMovement": {
        "monthly": [
          {
            "month": "Oct'25",
            "value": 577272108,
            "label": "Oct'25"
          },
          {
            "month": "Nov'25",
            "value": -142955471,
            "label": "Nov'25"
          },
          {
            "month": "Dec'25",
            "value": 225841396,
            "label": "Dec'25"
          }
        ]
      }
    },
    "collection": {
      "cei": {
        "overall": 84.6,
        "monthly": [
          {
            "month": "Oct'25",
            "value": 83.7
          },
          {
            "month": "Nov'25",
            "value": 85.3
          },
          {
            "month": "Dec'25",
            "value": 84.9
          }
        ]
      },
      "onTimePayment": {
        "weekly": [
          {
            "week": "W28",
            "value": 0
          },
          {
            "week": "W29",
            "value": 0
          },
          {
            "week": "W30",
            "value": 0
          },
          {
            "week": "W31",
            "value": 0
          },
          {
            "week": "W32",
            "value": 0
          },
          {
            "week": "W33",
            "value": 0
          },
          {
            "week": "W34",
            "value": 0
          },
          {
            "week": "W35",
            "value": 0
          },
          {
            "week": "W36",
            "value": 0
          },
          {
            "week": "W37",
            "value": 0
          },
          {
            "week": "W38",
            "value": 0
          },
          {
            "week": "W39",
            "value": 0
          },
          {
            "week": "W40",
            "value": 0
          }
        ]
      },
      "collectionEffectiveness": {
        "weekly": [
          {
            "week": "W28",
            "value": 0
          },
          {
            "week": "W29",
            "value": 0
          },
          {
            "week": "W30",
            "value": 0
          },
          {
            "week": "W31",
            "value": 0
          },
          {
            "week": "W32",
            "value": 0
          },
          {
            "week": "W33",
            "value": 0
          },
          {
            "week": "W34",
            "value": 0
          },
          {
            "week": "W35",
            "value": 0
          },
          {
            "week": "W36",
            "value": 0
          },
          {
            "week": "W37",
            "value": 0
          },
          {
            "week": "W38",
            "value": 0
          },
          {
            "week": "W39",
            "value": 0
          },
          {
            "week": "W40",
            "value": 0
          }
        ]
      },
      "creditPeriodEffectiveness": {
        "data": [
          {
            "creditPeriod": "7 days",
            "value": 77.7
          },
          {
            "creditPeriod": "15 days",
            "value": 61.8
          },
          {
            "creditPeriod": "30 days",
            "value": 68.9
          },
          {
            "creditPeriod": "45 days",
            "value": 82.7
          },
          {
            "creditPeriod": "60 days",
            "value": 79.2
          }
        ]
      }
    },
    "aging": {
      "buckets": [
        {
          "bucket": "Not Due",
          "key": "NOT_DUE",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#16a34a"
        },
        {
          "bucket": "1-7 days",
          "key": "1_7",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#22c55e"
        },
        {
          "bucket": "8-15 days",
          "key": "8_15",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#3b82f6"
        },
        {
          "bucket": "16-30 days",
          "key": "16_30",
          "count": 0,
          "amount": 0,
          "percentage": 0,
          "color": "#eab308"
        },
        {
          "bucket": "31-45 days",
          "key": "31_45",
          "count": 17,
          "amount": 156381036,
          "percentage": 2.5,
          "color": "#d97706"
        },
        {
          "bucket": "46-60 days",
          "key": "46_60",
          "count": 87,
          "amount": 748895674,
          "percentage": 12.1,
          "color": "#ea580c"
        },
        {
          "bucket": "60+ days",
          "key": "60_PLUS",
          "count": 1467,
          "amount": 5274202314,
          "percentage": 85.4,
          "color": "#dc2626"
        }
      ],
      "overdueDensity": {
        "count": 100,
        "value": 100
      },
      "peakExposure": {
        "amount": 168769906,
        "invoiceNo": "2025006542",
        "companyCode": "3000",
        "daysOverdue": 170
      }
    },
    "operational": {
      "invoiceToCash": {
        "p50": 37,
        "p90": 64
      },
      "creditPeriodUtilization": {
        "overall": 132.4,
        "monthly": [
          {
            "month": "Oct'25",
            "value": 132.5
          },
          {
            "month": "Nov'25",
            "value": 135.7
          },
          {
            "month": "Dec'25",
            "value": 129.3
          }
        ]
      },
      "daysToClearBacklog": {
        "weekly": [
          {
            "week": "W28",
            "value": 384.1
          },
          {
            "week": "W29",
            "value": 999
          },
          {
            "week": "W30",
            "value": 705
          },
          {
            "week": "W31",
            "value": 999
          },
          {
            "week": "W32",
            "value": 430.4
          },
          {
            "week": "W33",
            "value": 999
          },
          {
            "week": "W34",
            "value": 762.2
          },
          {
            "week": "W35",
            "value": 999
          },
          {
            "week": "W36",
            "value": 999
          },
          {
            "week": "W37",
            "value": 40.5
          },
          {
            "week": "W38",
            "value": 999
          },
          {
            "week": "W39",
            "value": 999
          },
          {
            "week": "W40",
            "value": 88.6
          }
        ]
      }
    },
    "advanced": {
      "dsoBridge": {
        "blendedDSO": 15.9,
        "segments": [
          {
            "segment": "STRATEGIC",
            "dso": 8.9,
            "weight": 34.5,
            "contribution": -2.4
          },
          {
            "segment": "KEY",
            "dso": 16.9,
            "weight": 38.7,
            "contribution": 0.4
          },
          {
            "segment": "STANDARD",
            "dso": 22.9,
            "weight": 17.7,
            "contribution": 1.2
          },
          {
            "segment": "SMB",
            "dso": 24.5,
            "weight": 9.1,
            "contribution": 0.8
          }
        ]
      },
      "arHealthScore": {
        "score": 55,
        "grade": "C",
        "components": {
          "DSO": 100,
          "CEI": 85,
          "Overdue": 0,
          "Aging": 0,
          "Concentration": 70,
          "Trend": 53
        }
      },
      "termsMixDrag": {
        "weightedAvgTerms": 36.6,
        "avgActualPayDays": 37.2,
        "drag": 0.6
      },
      "carryingCost": {
        "dailyCost": 1693008,
        "monthlyCost": 50790239,
        "annualCost": 231054095,
        "avgDaysOutstanding": 136
      },
      "cashFlowLeakage": {
        "bestPossibleDSO": 36.6,
        "actualDSO": 15.9,
        "leakageDays": -20.7,
        "leakageINR": -8053500017
      },
      "companyCodePerformance": [
        {
          "code": "1000",
          "name": "HQ Operations India",
          "dso": 14.4,
          "overdueRatio": 100,
          "openAR": 2083047916,
          "invoiceCount": 514
        },
        {
          "code": "2000",
          "name": "Manufacturing Division",
          "dso": 14.8,
          "overdueRatio": 100,
          "openAR": 1742146805,
          "invoiceCount": 554
        },
        {
          "code": "3000",
          "name": "Services & Solutions",
          "dso": 18.6,
          "overdueRatio": 100,
          "openAR": 2354284304,
          "invoiceCount": 503
        }
      ],
      "segmentEfficiency": [
        {
          "segment": "STRATEGIC",
          "dso": 8.9,
          "collectionRate": 90.1,
          "overdueRatio": 100,
          "efficiencyScore": 0
        },
        {
          "segment": "KEY",
          "dso": 16.9,
          "collectionRate": 81.2,
          "overdueRatio": 100,
          "efficiencyScore": 0
        },
        {
          "segment": "STANDARD",
          "dso": 22.9,
          "collectionRate": 74.6,
          "overdueRatio": 100,
          "efficiencyScore": 0
        },
        {
          "segment": "SMB",
          "dso": 24.5,
          "collectionRate": 72.8,
          "overdueRatio": 100,
          "efficiencyScore": 0
        }
      ]
    }
  },
  "Q4": {
    "summary": {
      "totalInvoices": 7282,
      "openInvoices": 3504,
      "clearedInvoices": 3778,
      "overdueInvoices": 1363,
      "totalOpenAR": 19064246906,
      "overdueAR": 4055144014,
      "currentAR": 15009102892,
      "totalSales": 38462994479
    },
    "executive": {
      "dso": {
        "overall": 44.6,
        "monthly": [
          {
            "month": "Jan'26",
            "value": 5.4
          },
          {
            "month": "Feb'26",
            "value": 16.7
          },
          {
            "month": "Mar'26",
            "value": 23
          }
        ]
      },
      "overdueRatio": {
        "overall": 21.3,
        "monthly": [
          {
            "month": "Jan'26",
            "value": 100
          },
          {
            "month": "Feb'26",
            "value": 20.2
          },
          {
            "month": "Mar'26",
            "value": 3.2
          }
        ]
      },
      "revenueAtRisk": {
        "value": 9.3
      },
      "receivablesTurnover": {
        "overall": 6.2,
        "monthly": [
          {
            "month": "Jan'26",
            "value": 6
          },
          {
            "month": "Feb'26",
            "value": 2.6
          },
          {
            "month": "Mar'26",
            "value": 1.6
          }
        ]
      },
      "netARMovement": {
        "monthly": [
          {
            "month": "Jan'26",
            "value": 276575373,
            "label": "Jan'26"
          },
          {
            "month": "Feb'26",
            "value": 3965516825,
            "label": "Feb'26"
          },
          {
            "month": "Mar'26",
            "value": 3815280789,
            "label": "Mar'26"
          }
        ]
      }
    },
    "collection": {
      "cei": {
        "overall": 88.8,
        "monthly": [
          {
            "month": "Jan'26",
            "value": 84.7
          },
          {
            "month": "Feb'26",
            "value": 85
          },
          {
            "month": "Mar'26",
            "value": 96.7
          }
        ]
      },
      "onTimePayment": {
        "weekly": [
          {
            "week": "W41",
            "value": 0
          },
          {
            "week": "W42",
            "value": 0
          },
          {
            "week": "W43",
            "value": 0
          },
          {
            "week": "W44",
            "value": 0
          },
          {
            "week": "W45",
            "value": 0
          },
          {
            "week": "W46",
            "value": 0
          },
          {
            "week": "W47",
            "value": 0
          },
          {
            "week": "W48",
            "value": 0
          },
          {
            "week": "W49",
            "value": 0
          },
          {
            "week": "W50",
            "value": 0
          },
          {
            "week": "W51",
            "value": 0
          },
          {
            "week": "W52",
            "value": 0
          }
        ]
      },
      "collectionEffectiveness": {
        "weekly": [
          {
            "week": "W41",
            "value": 0
          },
          {
            "week": "W42",
            "value": 0
          },
          {
            "week": "W43",
            "value": 0
          },
          {
            "week": "W44",
            "value": 0
          },
          {
            "week": "W45",
            "value": 0
          },
          {
            "week": "W46",
            "value": 0
          },
          {
            "week": "W47",
            "value": 0
          },
          {
            "week": "W48",
            "value": 0
          },
          {
            "week": "W49",
            "value": 0
          },
          {
            "week": "W50",
            "value": 0
          },
          {
            "week": "W51",
            "value": 0
          },
          {
            "week": "W52",
            "value": 0
          }
        ]
      },
      "creditPeriodEffectiveness": {
        "data": [
          {
            "creditPeriod": "7 days",
            "value": 73.3
          },
          {
            "creditPeriod": "15 days",
            "value": 70.3
          },
          {
            "creditPeriod": "30 days",
            "value": 71.3
          },
          {
            "creditPeriod": "45 days",
            "value": 73.9
          },
          {
            "creditPeriod": "60 days",
            "value": 74.3
          }
        ]
      }
    },
    "aging": {
      "buckets": [
        {
          "bucket": "Not Due",
          "key": "NOT_DUE",
          "count": 2141,
          "amount": 15009102892,
          "percentage": 78.7,
          "color": "#16a34a"
        },
        {
          "bucket": "1-7 days",
          "key": "1_7",
          "count": 284,
          "amount": 892211204,
          "percentage": 4.7,
          "color": "#22c55e"
        },
        {
          "bucket": "8-15 days",
          "key": "8_15",
          "count": 222,
          "amount": 633316612,
          "percentage": 3.3,
          "color": "#3b82f6"
        },
        {
          "bucket": "16-30 days",
          "key": "16_30",
          "count": 297,
          "amount": 1129024743,
          "percentage": 5.9,
          "color": "#eab308"
        },
        {
          "bucket": "31-45 days",
          "key": "31_45",
          "count": 238,
          "amount": 638091959,
          "percentage": 3.3,
          "color": "#d97706"
        },
        {
          "bucket": "46-60 days",
          "key": "46_60",
          "count": 215,
          "amount": 547837932,
          "percentage": 2.9,
          "color": "#ea580c"
        },
        {
          "bucket": "60+ days",
          "key": "60_PLUS",
          "count": 107,
          "amount": 214661563,
          "percentage": 1.1,
          "color": "#dc2626"
        }
      ],
      "overdueDensity": {
        "count": 38.9,
        "value": 21.3
      },
      "peakExposure": {
        "amount": 162846544,
        "invoiceNo": "2026009301",
        "companyCode": "2000",
        "daysOverdue": 23
      }
    },
    "operational": {
      "invoiceToCash": {
        "p50": 27,
        "p90": 55
      },
      "creditPeriodUtilization": {
        "overall": 119.5,
        "monthly": [
          {
            "month": "Jan'26",
            "value": 127.8
          },
          {
            "month": "Feb'26",
            "value": 117.8
          },
          {
            "month": "Mar'26",
            "value": 89.5
          }
        ]
      },
      "daysToClearBacklog": {
        "weekly": [
          {
            "week": "W41",
            "value": 930.4
          },
          {
            "week": "W42",
            "value": 0
          },
          {
            "week": "W43",
            "value": 999
          },
          {
            "week": "W44",
            "value": 0
          },
          {
            "week": "W45",
            "value": 0
          },
          {
            "week": "W46",
            "value": 18.1
          },
          {
            "week": "W47",
            "value": 200.4
          },
          {
            "week": "W48",
            "value": 13.3
          },
          {
            "week": "W49",
            "value": 999
          },
          {
            "week": "W50",
            "value": 999
          },
          {
            "week": "W51",
            "value": 999
          },
          {
            "week": "W52",
            "value": 34.3
          }
        ]
      }
    },
    "advanced": {
      "dsoBridge": {
        "blendedDSO": 44.6,
        "segments": [
          {
            "segment": "STRATEGIC",
            "dso": 45.4,
            "weight": 35,
            "contribution": 0.3
          },
          {
            "segment": "KEY",
            "dso": 45.7,
            "weight": 38.6,
            "contribution": 0.4
          },
          {
            "segment": "STANDARD",
            "dso": 43.8,
            "weight": 16.8,
            "contribution": -0.1
          },
          {
            "segment": "SMB",
            "dso": 38.6,
            "weight": 9.6,
            "contribution": -0.6
          }
        ]
      },
      "arHealthScore": {
        "score": 60,
        "grade": "C",
        "components": {
          "DSO": 38,
          "CEI": 89,
          "Overdue": 79,
          "Aging": 79,
          "Concentration": 70,
          "Trend": 0
        }
      },
      "termsMixDrag": {
        "weightedAvgTerms": 45.5,
        "avgActualPayDays": 29.5,
        "drag": -16
      },
      "carryingCost": {
        "dailyCost": 5223081,
        "monthlyCost": 156692440,
        "annualCost": 176659100,
        "avgDaysOutstanding": 34
      },
      "cashFlowLeakage": {
        "bestPossibleDSO": 45.5,
        "actualDSO": 44.6,
        "leakageDays": -0.9,
        "leakageINR": -377315400
      },
      "companyCodePerformance": [
        {
          "code": "1000",
          "name": "HQ Operations India",
          "dso": 47.7,
          "overdueRatio": 17.6,
          "openAR": 6907270187,
          "invoiceCount": 1180
        },
        {
          "code": "2000",
          "name": "Manufacturing Division",
          "dso": 42,
          "overdueRatio": 23.8,
          "openAR": 5446964403,
          "invoiceCount": 1154
        },
        {
          "code": "3000",
          "name": "Services & Solutions",
          "dso": 43.8,
          "overdueRatio": 23,
          "openAR": 6710012316,
          "invoiceCount": 1170
        }
      ],
      "segmentEfficiency": [
        {
          "segment": "STRATEGIC",
          "dso": 45.4,
          "collectionRate": 49.5,
          "overdueRatio": 13.6,
          "efficiencyScore": 942
        },
        {
          "segment": "KEY",
          "dso": 45.7,
          "collectionRate": 49.2,
          "overdueRatio": 13.3,
          "efficiencyScore": 933
        },
        {
          "segment": "STANDARD",
          "dso": 43.8,
          "collectionRate": 51.3,
          "overdueRatio": 38.5,
          "efficiencyScore": 720
        },
        {
          "segment": "SMB",
          "dso": 38.6,
          "collectionRate": 57.1,
          "overdueRatio": 57.5,
          "efficiencyScore": 629
        }
      ]
    }
  },
  "All": {
    "summary": {
      "totalInvoices": 25000,
      "openInvoices": 7683,
      "clearedInvoices": 17317,
      "overdueInvoices": 5542,
      "totalOpenAR": 34218921368,
      "overdueAR": 19209818476,
      "currentAR": 15009102892,
      "totalSales": 129123080799
    },
    "executive": {
      "dso": {
        "overall": 96.7,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 4.9
          },
          {
            "month": "May'25",
            "value": 6
          },
          {
            "month": "Jun'25",
            "value": 4.3
          },
          {
            "month": "Jul'25",
            "value": 4.6
          },
          {
            "month": "Aug'25",
            "value": 4.9
          },
          {
            "month": "Sep'25",
            "value": 4.5
          },
          {
            "month": "Oct'25",
            "value": 5.5
          },
          {
            "month": "Nov'25",
            "value": 5.2
          },
          {
            "month": "Dec'25",
            "value": 5.2
          },
          {
            "month": "Jan'26",
            "value": 5.4
          },
          {
            "month": "Feb'26",
            "value": 16.7
          },
          {
            "month": "Mar'26",
            "value": 23
          }
        ]
      },
      "overdueRatio": {
        "overall": 56.1,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 100
          },
          {
            "month": "May'25",
            "value": 100
          },
          {
            "month": "Jun'25",
            "value": 100
          },
          {
            "month": "Jul'25",
            "value": 100
          },
          {
            "month": "Aug'25",
            "value": 100
          },
          {
            "month": "Sep'25",
            "value": 100
          },
          {
            "month": "Oct'25",
            "value": 100
          },
          {
            "month": "Nov'25",
            "value": 100
          },
          {
            "month": "Dec'25",
            "value": 100
          },
          {
            "month": "Jan'26",
            "value": 100
          },
          {
            "month": "Feb'26",
            "value": 20.2
          },
          {
            "month": "Mar'26",
            "value": 3.2
          }
        ]
      },
      "revenueAtRisk": {
        "value": 27.2
      },
      "receivablesTurnover": {
        "overall": 25.3,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 12.5
          },
          {
            "month": "May'25",
            "value": 5.7
          },
          {
            "month": "Jun'25",
            "value": 6.4
          },
          {
            "month": "Jul'25",
            "value": 7.1
          },
          {
            "month": "Aug'25",
            "value": 6.9
          },
          {
            "month": "Sep'25",
            "value": 6.1
          },
          {
            "month": "Oct'25",
            "value": 6.6
          },
          {
            "month": "Nov'25",
            "value": 5.6
          },
          {
            "month": "Dec'25",
            "value": 6.1
          },
          {
            "month": "Jan'26",
            "value": 6
          },
          {
            "month": "Feb'26",
            "value": 2.6
          },
          {
            "month": "Mar'26",
            "value": 1.6
          }
        ]
      },
      "netARMovement": {
        "monthly": [
          {
            "month": "Apr'25",
            "value": 1310684907,
            "label": "Apr'25"
          },
          {
            "month": "May'25",
            "value": 255256859,
            "label": "May'25"
          },
          {
            "month": "Jun'25",
            "value": -298261264,
            "label": "Jun'25"
          },
          {
            "month": "Jul'25",
            "value": 270788123,
            "label": "Jul'25"
          },
          {
            "month": "Aug'25",
            "value": 251373597,
            "label": "Aug'25"
          },
          {
            "month": "Sep'25",
            "value": -287264807,
            "label": "Sep'25"
          },
          {
            "month": "Oct'25",
            "value": 577272108,
            "label": "Oct'25"
          },
          {
            "month": "Nov'25",
            "value": -142955471,
            "label": "Nov'25"
          },
          {
            "month": "Dec'25",
            "value": 225841396,
            "label": "Dec'25"
          },
          {
            "month": "Jan'26",
            "value": 276575373,
            "label": "Jan'26"
          },
          {
            "month": "Feb'26",
            "value": 3965516825,
            "label": "Feb'26"
          },
          {
            "month": "Mar'26",
            "value": 3815280789,
            "label": "Mar'26"
          }
        ]
      }
    },
    "collection": {
      "cei": {
        "overall": 86.1,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 83.7
          },
          {
            "month": "May'25",
            "value": 83.2
          },
          {
            "month": "Jun'25",
            "value": 87.8
          },
          {
            "month": "Jul'25",
            "value": 86
          },
          {
            "month": "Aug'25",
            "value": 85.5
          },
          {
            "month": "Sep'25",
            "value": 87.3
          },
          {
            "month": "Oct'25",
            "value": 83.7
          },
          {
            "month": "Nov'25",
            "value": 85.3
          },
          {
            "month": "Dec'25",
            "value": 84.9
          },
          {
            "month": "Jan'26",
            "value": 84.7
          },
          {
            "month": "Feb'26",
            "value": 85
          },
          {
            "month": "Mar'26",
            "value": 96.7
          }
        ]
      },
      "onTimePayment": {
        "weekly": [
          {
            "week": "W1",
            "value": 0
          },
          {
            "week": "W2",
            "value": 0
          },
          {
            "week": "W3",
            "value": 0
          },
          {
            "week": "W4",
            "value": 0
          },
          {
            "week": "W5",
            "value": 0
          },
          {
            "week": "W6",
            "value": 0
          },
          {
            "week": "W7",
            "value": 0
          },
          {
            "week": "W8",
            "value": 0
          },
          {
            "week": "W9",
            "value": 0
          },
          {
            "week": "W10",
            "value": 0
          },
          {
            "week": "W11",
            "value": 0
          },
          {
            "week": "W12",
            "value": 0
          },
          {
            "week": "W13",
            "value": 0
          },
          {
            "week": "W14",
            "value": 0
          },
          {
            "week": "W15",
            "value": 0
          },
          {
            "week": "W16",
            "value": 0
          },
          {
            "week": "W17",
            "value": 0
          },
          {
            "week": "W18",
            "value": 0
          },
          {
            "week": "W19",
            "value": 0
          },
          {
            "week": "W20",
            "value": 0
          },
          {
            "week": "W21",
            "value": 0
          },
          {
            "week": "W22",
            "value": 0
          },
          {
            "week": "W23",
            "value": 0
          },
          {
            "week": "W24",
            "value": 0
          },
          {
            "week": "W25",
            "value": 0
          },
          {
            "week": "W26",
            "value": 0
          },
          {
            "week": "W27",
            "value": 0
          },
          {
            "week": "W28",
            "value": 0
          },
          {
            "week": "W29",
            "value": 0
          },
          {
            "week": "W30",
            "value": 0
          },
          {
            "week": "W31",
            "value": 0
          },
          {
            "week": "W32",
            "value": 0
          },
          {
            "week": "W33",
            "value": 0
          },
          {
            "week": "W34",
            "value": 0
          },
          {
            "week": "W35",
            "value": 0
          },
          {
            "week": "W36",
            "value": 0
          },
          {
            "week": "W37",
            "value": 0
          },
          {
            "week": "W38",
            "value": 0
          },
          {
            "week": "W39",
            "value": 0
          },
          {
            "week": "W40",
            "value": 0
          },
          {
            "week": "W41",
            "value": 0
          },
          {
            "week": "W42",
            "value": 0
          },
          {
            "week": "W43",
            "value": 0
          },
          {
            "week": "W44",
            "value": 0
          },
          {
            "week": "W45",
            "value": 0
          },
          {
            "week": "W46",
            "value": 0
          },
          {
            "week": "W47",
            "value": 0
          },
          {
            "week": "W48",
            "value": 0
          },
          {
            "week": "W49",
            "value": 0
          },
          {
            "week": "W50",
            "value": 0
          },
          {
            "week": "W51",
            "value": 0
          },
          {
            "week": "W52",
            "value": 0
          }
        ]
      },
      "collectionEffectiveness": {
        "weekly": [
          {
            "week": "W1",
            "value": 0
          },
          {
            "week": "W2",
            "value": 0
          },
          {
            "week": "W3",
            "value": 0
          },
          {
            "week": "W4",
            "value": 0
          },
          {
            "week": "W5",
            "value": 0
          },
          {
            "week": "W6",
            "value": 0
          },
          {
            "week": "W7",
            "value": 0
          },
          {
            "week": "W8",
            "value": 0
          },
          {
            "week": "W9",
            "value": 0
          },
          {
            "week": "W10",
            "value": 0
          },
          {
            "week": "W11",
            "value": 0
          },
          {
            "week": "W12",
            "value": 0
          },
          {
            "week": "W13",
            "value": 0
          },
          {
            "week": "W14",
            "value": 0
          },
          {
            "week": "W15",
            "value": 0
          },
          {
            "week": "W16",
            "value": 0
          },
          {
            "week": "W17",
            "value": 0
          },
          {
            "week": "W18",
            "value": 0
          },
          {
            "week": "W19",
            "value": 0
          },
          {
            "week": "W20",
            "value": 0
          },
          {
            "week": "W21",
            "value": 0
          },
          {
            "week": "W22",
            "value": 0
          },
          {
            "week": "W23",
            "value": 0
          },
          {
            "week": "W24",
            "value": 0
          },
          {
            "week": "W25",
            "value": 0
          },
          {
            "week": "W26",
            "value": 0
          },
          {
            "week": "W27",
            "value": 0
          },
          {
            "week": "W28",
            "value": 0
          },
          {
            "week": "W29",
            "value": 0
          },
          {
            "week": "W30",
            "value": 0
          },
          {
            "week": "W31",
            "value": 0
          },
          {
            "week": "W32",
            "value": 0
          },
          {
            "week": "W33",
            "value": 0
          },
          {
            "week": "W34",
            "value": 0
          },
          {
            "week": "W35",
            "value": 0
          },
          {
            "week": "W36",
            "value": 0
          },
          {
            "week": "W37",
            "value": 0
          },
          {
            "week": "W38",
            "value": 0
          },
          {
            "week": "W39",
            "value": 0
          },
          {
            "week": "W40",
            "value": 0
          },
          {
            "week": "W41",
            "value": 0
          },
          {
            "week": "W42",
            "value": 0
          },
          {
            "week": "W43",
            "value": 0
          },
          {
            "week": "W44",
            "value": 0
          },
          {
            "week": "W45",
            "value": 0
          },
          {
            "week": "W46",
            "value": 0
          },
          {
            "week": "W47",
            "value": 0
          },
          {
            "week": "W48",
            "value": 0
          },
          {
            "week": "W49",
            "value": 0
          },
          {
            "week": "W50",
            "value": 0
          },
          {
            "week": "W51",
            "value": 0
          },
          {
            "week": "W52",
            "value": 0
          }
        ]
      },
      "creditPeriodEffectiveness": {
        "data": [
          {
            "creditPeriod": "7 days",
            "value": 71
          },
          {
            "creditPeriod": "15 days",
            "value": 64.7
          },
          {
            "creditPeriod": "30 days",
            "value": 70.6
          },
          {
            "creditPeriod": "45 days",
            "value": 79.5
          },
          {
            "creditPeriod": "60 days",
            "value": 78.5
          }
        ]
      }
    },
    "aging": {
      "buckets": [
        {
          "bucket": "Not Due",
          "key": "NOT_DUE",
          "count": 2141,
          "amount": 15009102892,
          "percentage": 43.9,
          "color": "#16a34a"
        },
        {
          "bucket": "1-7 days",
          "key": "1_7",
          "count": 284,
          "amount": 892211204,
          "percentage": 2.6,
          "color": "#22c55e"
        },
        {
          "bucket": "8-15 days",
          "key": "8_15",
          "count": 222,
          "amount": 633316612,
          "percentage": 1.9,
          "color": "#3b82f6"
        },
        {
          "bucket": "16-30 days",
          "key": "16_30",
          "count": 297,
          "amount": 1129024743,
          "percentage": 3.3,
          "color": "#eab308"
        },
        {
          "bucket": "31-45 days",
          "key": "31_45",
          "count": 255,
          "amount": 794472995,
          "percentage": 2.3,
          "color": "#d97706"
        },
        {
          "bucket": "46-60 days",
          "key": "46_60",
          "count": 302,
          "amount": 1296733606,
          "percentage": 3.8,
          "color": "#ea580c"
        },
        {
          "bucket": "60+ days",
          "key": "60_PLUS",
          "count": 4182,
          "amount": 14464059316,
          "percentage": 42.3,
          "color": "#dc2626"
        }
      ],
      "overdueDensity": {
        "count": 72.1,
        "value": 56.1
      },
      "peakExposure": {
        "amount": 168769906,
        "invoiceNo": "2025006542",
        "companyCode": "3000",
        "daysOverdue": 170
      }
    },
    "operational": {
      "invoiceToCash": {
        "p50": 36,
        "p90": 62
      },
      "creditPeriodUtilization": {
        "overall": 129.3,
        "monthly": [
          {
            "month": "Apr'25",
            "value": 135.4
          },
          {
            "month": "May'25",
            "value": 131.4
          },
          {
            "month": "Jun'25",
            "value": 132.6
          },
          {
            "month": "Jul'25",
            "value": 132.9
          },
          {
            "month": "Aug'25",
            "value": 130.8
          },
          {
            "month": "Sep'25",
            "value": 127.3
          },
          {
            "month": "Oct'25",
            "value": 132.5
          },
          {
            "month": "Nov'25",
            "value": 135.7
          },
          {
            "month": "Dec'25",
            "value": 129.3
          },
          {
            "month": "Jan'26",
            "value": 127.8
          },
          {
            "month": "Feb'26",
            "value": 117.8
          },
          {
            "month": "Mar'26",
            "value": 89.5
          }
        ]
      },
      "daysToClearBacklog": {
        "weekly": [
          {
            "week": "W1",
            "value": 0
          },
          {
            "week": "W2",
            "value": 0
          },
          {
            "week": "W3",
            "value": 0
          },
          {
            "week": "W4",
            "value": 0
          },
          {
            "week": "W5",
            "value": 0
          },
          {
            "week": "W6",
            "value": 0
          },
          {
            "week": "W7",
            "value": 0
          },
          {
            "week": "W8",
            "value": 0
          },
          {
            "week": "W9",
            "value": 0
          },
          {
            "week": "W10",
            "value": 0
          },
          {
            "week": "W11",
            "value": 0
          },
          {
            "week": "W12",
            "value": 0
          },
          {
            "week": "W13",
            "value": 0
          },
          {
            "week": "W14",
            "value": 71.8
          },
          {
            "week": "W15",
            "value": 190.9
          },
          {
            "week": "W16",
            "value": 20.7
          },
          {
            "week": "W17",
            "value": 85.3
          },
          {
            "week": "W18",
            "value": 78.1
          },
          {
            "week": "W19",
            "value": 0
          },
          {
            "week": "W20",
            "value": 39.5
          },
          {
            "week": "W21",
            "value": 430.3
          },
          {
            "week": "W22",
            "value": 0
          },
          {
            "week": "W23",
            "value": 999
          },
          {
            "week": "W24",
            "value": 471.6
          },
          {
            "week": "W25",
            "value": 0
          },
          {
            "week": "W26",
            "value": 22
          },
          {
            "week": "W27",
            "value": 12
          },
          {
            "week": "W28",
            "value": 384.1
          },
          {
            "week": "W29",
            "value": 999
          },
          {
            "week": "W30",
            "value": 705
          },
          {
            "week": "W31",
            "value": 999
          },
          {
            "week": "W32",
            "value": 430.4
          },
          {
            "week": "W33",
            "value": 999
          },
          {
            "week": "W34",
            "value": 762.2
          },
          {
            "week": "W35",
            "value": 999
          },
          {
            "week": "W36",
            "value": 999
          },
          {
            "week": "W37",
            "value": 40.5
          },
          {
            "week": "W38",
            "value": 999
          },
          {
            "week": "W39",
            "value": 999
          },
          {
            "week": "W40",
            "value": 88.6
          },
          {
            "week": "W41",
            "value": 930.4
          },
          {
            "week": "W42",
            "value": 0
          },
          {
            "week": "W43",
            "value": 999
          },
          {
            "week": "W44",
            "value": 0
          },
          {
            "week": "W45",
            "value": 0
          },
          {
            "week": "W46",
            "value": 18.1
          },
          {
            "week": "W47",
            "value": 200.4
          },
          {
            "week": "W48",
            "value": 13.3
          },
          {
            "week": "W49",
            "value": 999
          },
          {
            "week": "W50",
            "value": 999
          },
          {
            "week": "W51",
            "value": 999
          },
          {
            "week": "W52",
            "value": 34.3
          }
        ]
      }
    },
    "advanced": {
      "dsoBridge": {
        "blendedDSO": 96.7,
        "segments": [
          {
            "segment": "STRATEGIC",
            "dso": 77.9,
            "weight": 34.1,
            "contribution": -6.4
          },
          {
            "segment": "KEY",
            "dso": 99.5,
            "weight": 38.8,
            "contribution": 1.1
          },
          {
            "segment": "STANDARD",
            "dso": 114.5,
            "weight": 17.5,
            "contribution": 3.1
          },
          {
            "segment": "SMB",
            "dso": 119.9,
            "weight": 9.6,
            "contribution": 2.2
          }
        ]
      },
      "arHealthScore": {
        "score": 46,
        "grade": "D",
        "components": {
          "DSO": 0,
          "CEI": 86,
          "Overdue": 44,
          "Aging": 44,
          "Concentration": 76,
          "Trend": 26
        }
      },
      "termsMixDrag": {
        "weightedAvgTerms": 41.5,
        "avgActualPayDays": 35.5,
        "drag": -6
      },
      "carryingCost": {
        "dailyCost": 9375047,
        "monthlyCost": 281251409,
        "annualCost": 1272801425,
        "avgDaysOutstanding": 136
      },
      "cashFlowLeakage": {
        "bestPossibleDSO": 41.5,
        "actualDSO": 96.7,
        "leakageDays": 55.2,
        "leakageINR": 19538505540
      },
      "companyCodePerformance": [
        {
          "code": "1000",
          "name": "HQ Operations India",
          "dso": 96.8,
          "overdueRatio": 51.9,
          "openAR": 11820093407,
          "invoiceCount": 2559
        },
        {
          "code": "2000",
          "name": "Manufacturing Division",
          "dso": 86.6,
          "overdueRatio": 57.6,
          "openAR": 9792557250,
          "invoiceCount": 2548
        },
        {
          "code": "3000",
          "name": "Services & Solutions",
          "dso": 106.3,
          "overdueRatio": 59,
          "openAR": 12606270711,
          "invoiceCount": 2576
        }
      ],
      "segmentEfficiency": [
        {
          "segment": "STRATEGIC",
          "dso": 77.9,
          "collectionRate": 78.6,
          "overdueRatio": 37.6,
          "efficiencyScore": 630
        },
        {
          "segment": "KEY",
          "dso": 99.5,
          "collectionRate": 72.7,
          "overdueRatio": 52.1,
          "efficiencyScore": 350
        },
        {
          "segment": "STANDARD",
          "dso": 114.5,
          "collectionRate": 68.6,
          "overdueRatio": 72.7,
          "efficiencyScore": 163
        },
        {
          "segment": "SMB",
          "dso": 119.9,
          "collectionRate": 67.2,
          "overdueRatio": 83.5,
          "efficiencyScore": 93
        }
      ]
    }
  }
} as any;
